---

- name: Cisco show ip interface + ip route
  hosts: ioss
  gather_facts: false

  tasks:
    - name: run show ip interface brief + ip route
      ios_command:
        commands:
          - show ip interface brief
          - show ip route
      register: output

    - name: print output
      debug:
        var: output.stdout_lines

