---

- name: Cisco show version example
  hosts: ioss
  gather_facts: false

  tasks:
    - name: run show version example
      ios_command:
        commands: show version | incl Version
      register: output

    - name: print output
      debug:
        var: output.stdout_lines

